export type SceneObjectKind =
  | "building"
  | "pine"
  | "cherry"
  | "bench"
  | "people";

export type CropBox = {
  x: number;
  y: number;
  width: number;
  height: number;
};

export type SceneObject = {
  id: string;
  kind: SceneObjectKind;
  src: string;
  x: number;
  y: number;
  width: number;
  mobileX?: number;
  mobileY?: number;
  mobileWidth?: number;
  crop: CropBox;
  rotation: number;
  scale: number;
  z: number;
  depth: number;
  parallax: number;
  speed: number;
  entranceDelay: number;
  opacity?: number;
  blendMode?: "normal" | "multiply";
};

export const HERO_SCENE_VIEWBOX = 1500;

export const sceneObjects: SceneObject[] = [
  {
    id: "left-architecture",
    kind: "building",
    src: "/images/hero-parallax/17.svg",
    x: -4,
    y: 13,
    width: 50,
    mobileX: -32,
    mobileY: 34,
    mobileWidth: 104,
    crop: { x: 22, y: 455, width: 1396, height: 1031 },
    rotation: 0,
    scale: 1,
    z: 8,
    depth: 0.18,
    parallax: 0.18,
    speed: 0.66,
    entranceDelay: 0.22,
    opacity: 0.98,
  },
  {
    id: "cathedral-tower",
    kind: "building",
    src: "/images/hero-parallax/16.svg",
    x: 60,
    y: -2,
    width: 15,
    mobileX: 49,
    mobileY: 8,
    mobileWidth: 31,
    crop: { x: 0, y: 218, width: 461, height: 1176 },
    rotation: 0,
    scale: 1,
    z: 9,
    depth: 0.22,
    parallax: 0.22,
    speed: 0.7,
    entranceDelay: 0.28,
  },
  {
    id: "right-architecture",
    kind: "building",
    src: "/images/hero-parallax/6.svg",
    x: 70,
    y: 25,
    width: 35,
    mobileX: 61,
    mobileY: 45,
    mobileWidth: 68,
    crop: { x: 0, y: 321, width: 1476, height: 1179 },
    rotation: 0,
    scale: 1,
    z: 7,
    depth: 0.2,
    parallax: 0.18,
    speed: 0.66,
    entranceDelay: 0.34,
    opacity: 0.95,
  },
  {
    id: "center-pine",
    kind: "pine",
    src: "/images/hero-parallax/20.svg",
    x: 58,
    y: 31,
    width: 8,
    mobileX: 47,
    mobileY: 52,
    mobileWidth: 18,
    crop: { x: 414, y: 98, width: 665, height: 1252 },
    rotation: -2,
    scale: 1,
    z: 13,
    depth: 0.42,
    parallax: 0.34,
    speed: 0.74,
    entranceDelay: 0.58,
    opacity: 0.92,
  },
  {
    id: "right-pine",
    kind: "pine",
    src: "/images/hero-parallax/18.svg",
    x: 95,
    y: 45,
    width: 7,
    mobileX: 82,
    mobileY: 58,
    mobileWidth: 15,
    crop: { x: 61, y: 246, width: 703, height: 1156 },
    rotation: 2,
    scale: 1,
    z: 12,
    depth: 0.42,
    parallax: 0.34,
    speed: 0.74,
    entranceDelay: 0.62,
    opacity: 0.78,
  },
  {
    id: "front-left-blossom",
    kind: "cherry",
    src: "/images/hero-parallax/3.svg",
    x: -3,
    y: 61,
    width: 23,
    mobileX: -26,
    mobileY: 62,
    mobileWidth: 58,
    crop: { x: 73, y: 27, width: 1374, height: 1388 },
    rotation: -2,
    scale: 1.06,
    z: 31,
    depth: 0.74,
    parallax: 0.72,
    speed: 1.08,
    entranceDelay: 0.74,
  },
  {
    id: "left-cream-blossom",
    kind: "cherry",
    src: "/images/hero-parallax/10.svg",
    x: 17,
    y: 62,
    width: 14,
    mobileX: 12,
    mobileY: 64,
    mobileWidth: 34,
    crop: { x: 57, y: 0, width: 1338, height: 1449 },
    rotation: -1,
    scale: 1.03,
    z: 24,
    depth: 0.82,
    parallax: 0.8,
    speed: 1.12,
    entranceDelay: 0.8,
  },
  {
    id: "left-magenta-blossom",
    kind: "cherry",
    src: "/images/hero-parallax/11.svg",
    x: 23,
    y: 60,
    width: 22,
    mobileX: 28,
    mobileY: 63,
    mobileWidth: 48,
    crop: { x: 0, y: 61, width: 1246, height: 1428 },
    rotation: -1,
    scale: 1.06,
    z: 35,
    depth: 0.92,
    parallax: 0.9,
    speed: 1.16,
    entranceDelay: 0.86,
  },
  {
    id: "right-mid-blossom",
    kind: "cherry",
    src: "/images/hero-parallax/12.svg",
    x: 68,
    y: 61,
    width: 14,
    mobileX: 118,
    mobileY: 66,
    mobileWidth: 36,
    crop: { x: 17, y: 362, width: 1448, height: 1059 },
    rotation: 1,
    scale: 1.03,
    z: 25,
    depth: 1.08,
    parallax: 1.04,
    speed: 1.18,
    entranceDelay: 1,
  },
  {
    id: "right-front-blossom",
    kind: "cherry",
    src: "/images/hero-parallax/13.svg",
    x: 81,
    y: 60,
    width: 19,
    mobileX: 140,
    mobileY: 65,
    mobileWidth: 38,
    crop: { x: 74, y: 12, width: 1317, height: 1488 },
    rotation: 2,
    scale: 1.06,
    z: 32,
    depth: 1.12,
    parallax: 1.1,
    speed: 1.2,
    entranceDelay: 1.04,
  },
  {
    id: "walking-people",
    kind: "people",
    src: "/images/hero-parallax/22.svg",
    x: 52,
    y: 64,
    width: 6,
    mobileX: 88,
    mobileY: 77,
    mobileWidth: 16,
    crop: { x: 326, y: 105, width: 847, height: 1336 },
    rotation: 0,
    scale: 1,
    z: 42,
    depth: 1.38,
    parallax: 1.24,
    speed: 1.22,
    entranceDelay: 1.12,
  },
  {
    id: "bench-readers",
    kind: "bench",
    src: "/images/hero-parallax/23.svg",
    x: 31,
    y: 82,
    width: 11,
    mobileX: 36,
    mobileY: 84,
    mobileWidth: 21,
    crop: { x: 208, y: 536, width: 926, height: 653 },
    rotation: 0,
    scale: 1,
    z: 45,
    depth: 1.48,
    parallax: 1.34,
    speed: 1.26,
    entranceDelay: 1.24,
  },
];
